#ifndef SUPERVISOR_CONSTANTS_H
#define SUPERVISOR_CONSTANTS_H

#define SUPERVISOR_FLAGS_CREATESTOPPED 0xFFFF
#define SUPERVISOR_FLAGS_RESTARTTIMES(times) ((times & 0xF) << 16)
#define SUPERVISOR_STATUS_RUNNING 0x1
#define SUPERVISOR_STATUS_PENDING 0x2
#define SUPERVISOR_STATUS_STOPPED 0x4
#define SUPERVISOR_STATUS_TERMINATED 0x8
#define SUPERVISOR_STATUS_CRASHED 0x10
#define KILL_SERVICE 1
#define STATUS_SERVICE 2
#define SUSPEND_SERVICE 3
#define RESUME_SERVICE 4
#define CANCEL_SERVICE 5
#define MAX_ARG_LEN 1024
#define MAX_ARGS 128
#define MAX_SUPERVISORS 128
#define MAX_SERVICES_PER_INSTANCE 128
#define RESPONSE_STR_SIZE 2048
#define MAX_SERVICE_NAME_LENGTH 128
#define MAX_PROGRAM_PATH_LENGTH 128
#define MAX_ARG_LENGTH 128
#define MAX_FORMATTED_SERVICE_NAME_LENGTH 256
#endif
